### ISSUE TITLE
panic in downlink.handleDataDownPayload

### ISSUE THREAD

**Issue by sko00o** [brocaar/lora-app-server#314]
### Is this a bug or a feature request?
bug

### What did you expect?
Because `pl.Object` won't be nil on this [line](https://github.com/brocaar/lora-app-server/blob/master/internal/downlink/downlink.go#L54), while DataDownPayload.Object not set in json.
Must set empty json raw bytes in DataDownPayload.Object. Example [here](https://play.golang.org/p/df4OT_uP1h8)

This will fix the problem.
```go
if pl.Object != nil && string(pl.Object) != "null" {...}
```

### What happened?
Got panic [here](https://github.com/brocaar/lora-app-server/blob/master/internal/downlink/downlink.go#L73) when DataDownPayload.Object not set.

### What version are your using?
commit 3f94bd61bf

### How can your issue be reproduced?
send json format payload without `object` element to downlink topic.

### Could you share your log output?

```sh
INFO[0009] integration/mqtt: publishing message          qos=0 topic=application/1/device/c4cd82a72b5bf406/rx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe93336]

goroutine 216 [running]:
github.com/brocaar/lora-app-server/internal/downlink.handleDataDownPayload.func1(0x142e3e0, 0xc000586230, 0x0, 0x0)
        /mnt/d/GoPro/lora-app-server/internal/downlink/downlink.go:73 +0x466
github.com/brocaar/lora-app-server/internal/storage.Transaction(0xc0005a7d98, 0x2c, 0x2c)
        /mnt/d/GoPro/lora-app-server/internal/storage/db.go:135 +0xaa
github.com/brocaar/lora-app-server/internal/downlink.handleDataDownPayload(0x1, 0x6f45b2ba782cdc4, 0x200, 0xc0003459b8, 0x4, 0x6
, 0xc0003459c0, 0x4, 0x8, 0x2a, ...)
        /mnt/d/GoPro/lora-app-server/internal/downlink/downlink.go:37 +0x49
github.com/brocaar/lora-app-server/internal/downlink.HandleDataDownPayloads.func1(0x1, 0x6f45b2ba782cdc4, 0x200, 0xc0003459b8, 0
x4, 0x6, 0xc0003459c0, 0x4, 0x8)
        /mnt/d/GoPro/lora-app-server/internal/downlink/downlink.go:26 +0x77
created by github.com/brocaar/lora-app-server/internal/downlink.HandleDataDownPayloads
        /mnt/d/GoPro/lora-app-server/internal/downlink/downlink.go:25 +0x155
```

**Comment by brocaar** [comment]
Thanks for reporting!
